name = "BiotSavartBCs"
uuid = "ec5a6caf-bdf7-41d0-b8e1-5fafde84e19f"
authors = ["Gabriel Weymouth"]
version = "1.0.0-DEV"

[deps]
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
WaterLily = "ed894a53-35f9-47f1-b17f-85db9237eebd"

[compat]
Atomix = "1"
GLMakie = "0.13.6"
JLD2 = "0.6.1"
KernelAbstractions = "0.9"
Plots = "1.41.1"
StaticArrays = "1.9"
TypedTables = "1.4.6"
WaterLily = "1.5"
julia = "1.10"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ForwardDiff", "SpecialFunctions"]
